(function(AD_CONFIG, LINKS, RT_CONFIG){
/*! Copyright 2015 Baidu Inc. All Rights Reserved. */
"";
"";
var baidu={version:"1.5.0"};baidu.guid="$BAIDU$";window[baidu.guid]=window[baidu.guid]||{};baidu.array=baidu.array||{};baidu.array.removeAt=function(b,a){return b.splice(a,1)[0]};baidu.dom=baidu.dom||{};baidu.dom.g=function(a){if("string"==typeof a||a instanceof String){return document.getElementById(a)}else{if(a&&a.nodeName&&(a.nodeType==1||a.nodeType==9)){return a}}return null};baidu.g=baidu.G=baidu.dom.g;baidu.dom._matchNode=function(a,c,d){a=baidu.dom.g(a);for(var b=a[d];b;b=b[c]){if(b.nodeType==1){return b}}return null};baidu.dom.first=function(a){return baidu.dom._matchNode(a,"nextSibling","firstChild")};baidu.dom.next=function(a){return baidu.dom._matchNode(a,"nextSibling","nextSibling")};baidu.cookie=baidu.cookie||{};baidu.cookie._isValidKey=function(a){return(new RegExp('^[^\\x00-\\x20\\x7f\\(\\)<>@,;:\\\\\\"\\[\\]\\?=\\{\\}\\/\\u0080-\\uffff]+\x24')).test(a)
};baidu.cookie.getRaw=function(b){if(baidu.cookie._isValidKey(b)){var c=new RegExp("(^| )"+b+"=([^;]*)(;|\x24)"),a=c.exec(document.cookie);if(a){return a[2]||null}}return null};baidu.cookie.get=function(a){var b=baidu.cookie.getRaw(a);if("string"==typeof b){b=decodeURIComponent(b);return b}return null};baidu.lang=baidu.lang||{};baidu.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};baidu.page=baidu.page||{};baidu.page.getViewWidth=function(){var b=document,a=b.compatMode=="BackCompat"?b.body:b.documentElement;return a.clientWidth};baidu.page.getScrollTop=function(){var a=document;return window.pageYOffset||a.documentElement.scrollTop||a.body.scrollTop};baidu.dom.prev=function(a){return baidu.dom._matchNode(a,"previousSibling","previousSibling")};baidu.cookie.setRaw=function(c,d,b){if(!baidu.cookie._isValidKey(c)){return
}b=b||{};var a=b.expires;if("number"==typeof b.expires){a=new Date();a.setTime(a.getTime()+b.expires)}document.cookie=c+"="+d+(b.path?"; path="+b.path:"")+(a?"; expires="+a.toGMTString():"")+(b.domain?"; domain="+b.domain:"")+(b.secure?"; secure":"")};baidu.cookie.remove=function(b,a){a=a||{};a.expires=new Date(0);baidu.cookie.setRaw(b,"",a)};baidu.string=baidu.string||{};(function(){var a=new RegExp("(^[\\s\\t\\xa0\\u3000]+)|([\\u3000\\xa0\\s\\t]+\x24)","g");baidu.string.trim=function(b){return String(b).replace(a,"")}})();baidu.trim=baidu.string.trim;baidu.string.escapeReg=function(a){return String(a).replace(new RegExp("([.*+?^=!:\x24{}()|[\\]/\\\\])","g"),"\\\x241")};baidu.dom.q=function(h,e,b){var j=[],d=baidu.string.trim,g,f,a,c;if(!(h=d(h))){return j}if("undefined"==typeof e){e=document
}else{e=baidu.dom.g(e);if(!e){return j}}b&&(b=d(b).toUpperCase());if(e.getElementsByClassName){a=e.getElementsByClassName(h);g=a.length;for(f=0;f<g;f++){c=a[f];if(b&&c.tagName!=b){continue}j[j.length]=c}}else{h=new RegExp("(^|\\s)"+baidu.string.escapeReg(h)+"(\\s|\x24)");a=b?e.getElementsByTagName(b):(e.all||e.getElementsByTagName("*"));g=a.length;for(f=0;f<g;f++){c=a[f];h.test(c.className)&&(j[j.length]=c)}}return j};baidu.q=baidu.Q=baidu.dom.q;baidu.sio=baidu.sio||{};baidu.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;baidu.sio._createScriptTag=function(b,a,c){b.setAttribute("type","text/javascript");c&&b.setAttribute("charset",c);
b.setAttribute("src",a);document.getElementsByTagName("head")[0].appendChild(b)};baidu.sio._removeScriptTag=function(b){if(b.clearAttributes){b.clearAttributes()}else{for(var a in b){if(b.hasOwnProperty(a)){delete b[a]}}}if(b&&b.parentNode){b.parentNode.removeChild(b)}b=null};baidu.sio.callByServer=function(a,m,n){var i=document.createElement("SCRIPT"),h="bd__cbs__",k,e,o=n||{},d=o.charset,f=o.queryField||"callback",l=o.timeOut||0,b,c=new RegExp("(\\?|&)"+f+"=([^&]*)"),g;if(baidu.lang.isFunction(m)){k=h+Math.floor(Math.random()*2147483648).toString(36);window[k]=j(0)}else{if(baidu.lang.isString(m)){k=m}else{if(g=c.exec(a)){k=g[2]}}}if(l){b=setTimeout(j(1),l)}a=a.replace(c,"\x241"+f+"="+k);if(a.search(c)<0){a+=(a.indexOf("?")<0?"?":"&")+f+"="+k}baidu.sio._createScriptTag(i,a,d);function j(p){return function(){try{if(p){o.onfailure&&o.onfailure()
}else{m.apply(window,arguments);clearTimeout(b)}window[k]=null;delete window[k]}catch(q){}finally{baidu.sio._removeScriptTag(i)}}}};baidu.page.getViewHeight=function(){var b=document,a=b.compatMode=="BackCompat"?b.body:b.documentElement;return a.clientHeight};baidu.dom.getDocument=function(a){a=baidu.dom.g(a);return a.nodeType==9?a:a.ownerDocument||a.document};baidu.dom._g=function(a){if(baidu.lang.isString(a)){return document.getElementById(a)}return a};baidu._g=baidu.dom._g;baidu.browser=baidu.browser||{};baidu.browser.ie=baidu.ie=/msie (\d+\.\d+)/i.test(navigator.userAgent)?(document.documentMode||+RegExp["\x241"]):undefined;baidu.dom.getComputedStyle=function(b,a){b=baidu.dom._g(b);var d=baidu.dom.getDocument(b),c;if(d.defaultView&&d.defaultView.getComputedStyle){c=d.defaultView.getComputedStyle(b,null);
if(c){return c[a]||c.getPropertyValue(a)}}return""};baidu.dom._styleFixer=baidu.dom._styleFixer||{};baidu.dom._styleFilter=baidu.dom._styleFilter||[];baidu.dom._styleFilter.filter=function(b,e,f){for(var a=0,d=baidu.dom._styleFilter,c;c=d[a];a++){if(c=c[f]){e=c(b,e)}}return e};baidu.string.toCamelCase=function(a){if(a.indexOf("-")<0&&a.indexOf("_")<0){return a}return a.replace(/[-_][^-_]/g,function(b){return b.charAt(1).toUpperCase()})};baidu.dom.getStyle=function(c,b){var e=baidu.dom;c=e.g(c);b=baidu.string.toCamelCase(b);var d=c.style[b]||(c.currentStyle?c.currentStyle[b]:"")||e.getComputedStyle(c,b);if(!d){var a=e._styleFixer[b];if(a){d=a.get?a.get(c):baidu.dom.getStyle(c,a)}}if(a=e._styleFilter){d=a.filter(b,d,"get")}return d};baidu.getStyle=baidu.dom.getStyle;baidu.browser.opera=/opera(\/| )(\d+(\.\d+)?)(.+?(version\/(\d+(\.\d+)?)))?/i.test(navigator.userAgent)?+(RegExp["\x246"]||RegExp["\x242"]):undefined;
baidu.browser.isWebkit=/webkit/i.test(navigator.userAgent);baidu.browser.isGecko=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);baidu.browser.isStrict=document.compatMode=="CSS1Compat";baidu.dom.getPosition=function(a){a=baidu.dom.g(a);var j=baidu.dom.getDocument(a),d=baidu.browser,g=baidu.dom.getStyle,c=d.isGecko>0&&j.getBoxObjectFor&&g(a,"position")=="absolute"&&(a.style.top===""||a.style.left===""),h={left:0,top:0},f=(d.ie&&!d.isStrict)?j.body:j.documentElement,k,b;if(a==f){return h}if(a.getBoundingClientRect){b=a.getBoundingClientRect();h.left=Math.floor(b.left)+Math.max(j.documentElement.scrollLeft,j.body.scrollLeft);h.top=Math.floor(b.top)+Math.max(j.documentElement.scrollTop,j.body.scrollTop);h.left-=j.documentElement.clientLeft;h.top-=j.documentElement.clientTop;
var i=j.body,l=parseInt(g(i,"borderLeftWidth")),e=parseInt(g(i,"borderTopWidth"));if(d.ie&&!d.isStrict){h.left-=isNaN(l)?2:l;h.top-=isNaN(e)?2:e}}else{k=a;do{h.left+=k.offsetLeft;h.top+=k.offsetTop;if(d.isWebkit>0&&g(k,"position")=="fixed"){h.left+=j.body.scrollLeft;h.top+=j.body.scrollTop;break}k=k.offsetParent}while(k&&k!=a);if(d.opera>0||(d.isWebkit>0&&g(a,"position")=="absolute")){h.top-=j.body.offsetTop}k=a.offsetParent;while(k&&k!=j.body){h.left-=k.scrollLeft;if(!d.opera||k.tagName!="TR"){h.top-=k.scrollTop}k=k.offsetParent}}return h};baidu.dom.getAncestorBy=function(a,b){a=baidu.dom.g(a);while((a=a.parentNode)&&a.nodeType==1){if(b(a)){return a}}return null};baidu.lang.toArray=function(b){if(b===null||b===undefined){return[]}if(baidu.lang.isArray(b)){return b}if(typeof b.length!=="number"||typeof b==="string"||baidu.lang.isFunction(b)){return[b]
}if(b.item){var a=b.length,c=new Array(a);while(a--){c[a]=b[a]}return c}return[].slice.call(b)};baidu.page.getScrollLeft=function(){var a=document;return window.pageXOffset||a.documentElement.scrollLeft||a.body.scrollLeft};baidu.array.indexOf=function(e,b,d){var a=e.length,c=b;d=d|0;if(d<0){d=Math.max(0,a+d)}for(;d<a;d++){if(d in e&&e[d]===b){return d}}return -1};baidu.lang.inherits=function(g,e,d){var c,f,a=g.prototype,b=new Function();b.prototype=e.prototype;f=g.prototype=new b();for(c in a){f[c]=a[c]}g.prototype.constructor=g;g.superClass=e.prototype;if("string"==typeof d){f._className=d}};baidu.inherits=baidu.lang.inherits;;
var p,r=r||{};r.global=this;r.La=!0;r.Na="en";r.Ma=!0;r.Ea=function(a){return void 0!==a};r.Da=function(a,b,c){a=a.split(".");c=c||r.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&r.Ea(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};r.Qa=function(a,b,c){r.Da(a,b,c)};r.Pa=function(a,b,c){a[b]=c};r.Sa=function(){return!1};r.Wa=function(){};r.Ra=function(){};var aa,s;if(s=/msie (\d+\.\d)/i.exec(navigator.userAgent))var t=document.documentMode||+s[1];if(s=/firefox\/(\d+\.\d)/i.exec(navigator.userAgent))var ba=+s[1];if(s=/opera\/(\d+\.\d)/i.exec(navigator.userAgent))var ca=+s[1];var da=navigator.userAgent,ea=da.match(/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i);ea&&!/chrome/i.test(da)&&(aa=+(ea[1]||ea[2]));var fa="CSS1Compat"===document.compatMode,ga=/webkit/i.test(navigator.userAgent);s=/UCBrowser\/(\d+\.\d)/i.exec(navigator.userAgent);window.$ECMA$=window.$ECMA$||{};window.$ECMA$._instances=window.$ECMA$._instances||{};(function(){var a=window.$ECMA$;a.ga=a.ga||1;return function(){return"ECMA__"+(a.ga++).toString(36)}})();function ha(a,b){if("function"===typeof b)for(var c in a)if(a.hasOwnProperty(c)&&!1===b.call(a,a[c],c))break}function u(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function ia(a){var b=Object.prototype.hasOwnProperty,c;if(!(a&&"[object Object]"===Object.prototype.toString.call(a)&&"isPrototypeOf"in a)||a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(c in a);return void 0===c||b.call(a,c)};var w=[];function x(a,b,c){function d(b){c.call(a,b)}b=b.replace(/^on/i,"");"string"===typeof a&&(a=document.getElementById(a));var e=b;b=b.toLowerCase();a.addEventListener?a.addEventListener(e,d,!1):a.attachEvent&&a.attachEvent("on"+e,d);w[w.length]=[a,b,c,d,e]}
function y(a,b,c){"string"===typeof a&&(a=document.getElementById(a));b=b.replace(/^on/i,"").toLowerCase();for(var d=w.length,e=!c,f,h;d--;)f=w[d],f[1]!==b||f[0]!==a||!e&&f[2]!==c||(h=f[4],f=f[3],a.removeEventListener?a.removeEventListener(h,f,!1):a.detachEvent&&a.detachEvent("on"+h,f),w.splice(d,1))}function ja(a){a.preventDefault?a.preventDefault():a.returnValue=!1}
(function(){function a(a,b){for(var c=0,d=a.length,e={};c<d;c++)e[a[c]]=b[a[c]],delete b[a[c]];return e}function b(b,c,d){d=u({},d);var e=a(k[c],d),f=[],h;for(h in e)e.hasOwnProperty(h)&&f.push(e[h]);e=document.createEvent(c);f.unshift(b);"KeyEvents"===c?e.initKeyEvent.apply(e,f):"MouseEvents"===c?e.initMouseEvent.apply(e,f):"UIEvents"===c?e.initUIEvent.apply(e,f):e.initEvent.apply(e,f);u(e,d);return e}function c(a){var b;document.createEventObject&&(b=document.createEventObject(),u(b,a));return b}
var d={Ta:1,Va:1,Ua:1},e={click:1,Oa:1,Xa:1,Ya:1,ab:1,$a:1,Za:1},f={abort:1,blur:1,Ca:1,error:1,focus:1,load:t?0:1,reset:1,resize:1,scroll:1,select:1,submit:1,bb:t?0:1},h={scroll:1,resize:1,reset:1,submit:1,Ca:1,select:1,error:1,abort:1},k={KeyEvents:"bubbles cancelable view ctrlKey altKey shiftKey metaKey keyCode charCode".split(" "),MouseEvents:"bubbles cancelable view detail screenX screenY clientX clientY ctrlKey altKey shiftKey metaKey button relatedTarget".split(" "),HTMLEvents:["bubbles","cancelable"],
UIEvents:["bubbles","cancelable","view","detail"],Events:["bubbles","cancelable"]};u(h,d);u(h,e);return function(q,n,g){n=n.replace(/^on/i,"");q=A.g(q);g=u({bubbles:!0,cancelable:!0,view:window,detail:1,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1,keyCode:0,charCode:0,button:0,relatedTarget:null},g);if(d[n]){var m=n;g=a(k.KeyEvents,g);var l;if(document.createEvent)try{l=b(m,"KeyEvents",g)}catch(v){try{l=b(m,"Events",g)}catch(D){l=b(m,"UIEvents",g)}}else g.keyCode=
0<g.charCode?g.charCode:g.keyCode,l=c(g);g=l}else if(e[n])l=n,g=a(k.MouseEvents,g),document.createEvent?(m=b(l,"MouseEvents",g),g.relatedTarget&&!m.relatedTarget&&("mouseout"===l.toLowerCase()?m.toElement=g.relatedTarget:"mouseover"===l.toLowerCase()&&(m.fromElement=g.relatedTarget))):(l=g,0===g.button?m=1:1===g.button?m=4:(m=g.button,m="[object Number]"===Object.prototype.toString.call(m)&&isFinite(m)?g.button:0),l.button=m,m=c(g)),g=m;else if(f[n]){l=n;g.bubbles=h.hasOwnProperty(l);g=a(k.HTMLEvents,
g);if(document.createEvent)try{m=b(l,"HTMLEvents",g)}catch(z){try{m=b(l,"UIEvents",g)}catch(J){m=b(l,"Events",g)}}else m=c(g);g=m}else throw Error(n+" is not support!");g&&(q.dispatchEvent?q.dispatchEvent(g):q.fireEvent&&q.fireEvent("on"+n,g))}})();var B;B=function(a,b,c){var d,e,f=a.length;if("function"===typeof b)for(e=0;e<f&&(d=a[e],d=b.call(c||a,d,e),!1!==d);e++);};var C="function"===typeof"".trim?function(a){return String(a).trim()}:function(a){return String(a).replace(/(^[\s\t\xa0\u3000\ufeff]+)|([\ufeff\u3000\xa0\s\t]+$)/g,"")};
function ka(a,b){a=String(a);var c=arguments[1];if("undefined"!==typeof c){if(ia(c))return a.replace(/\$\{(.+?)\}/g,function(a,b){var d=c[b];"function"===typeof d&&(d=d(b));return"undefined"===typeof d?"":d});var d=Array.prototype.slice.call(arguments,1),e=d.length;return a.replace(/\{(\d+)\}/g,function(a,b){b=parseInt(b,10);return b>=e?a:d[b]})}return a}function la(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})};function ma(a){return String(a).replace(/%/g,"%25").replace(/&/g,"%26").replace(/\+/g,"%2B").replace(/ /g,"%20").replace(/\//g,"%2F").replace(/#/g,"%23").replace(/=/g,"%3D")}function pa(a){var b=[],c;ha(a,function(a,e){if("[object Array]"===Object.prototype.toString.call(a))for(c=a.length;c--;)b.push(e+"="+ma(a[c]));else b.push(e+"="+ma(a))});return b.join("&")};function qa(a){a=a.split(".");for(var b=window,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b}function E(){return Math.floor(2147483648*Math.random()).toString(36)}var ra=RT_CONFIG.HOSTMAP;ra||(ra=RT_CONFIG.HOSTMAP={});"object"!==typeof RT_CONFIG||RT_CONFIG.HOST||(RT_CONFIG.HOST=function(a){return RT_CONFIG.HOSTMAP[a]||"http://"+a});function sa(a){var b=qa("bds.ready");"function"===typeof b&&b(function(){a()})}
var ta={"[object Boolean]":"boolean","[object Number]":"number","[object String]":"string","[object Function]":"function","[object Array]":"array","[object Date]":"date","[object RegExp]":"regexp","[object Object]":"object","[object Error]":"error"},ua=Object.prototype.toString;function va(a){return null==a?String(a):"object"===typeof a||"function"===typeof a?ta[ua.call(a)]||"object":typeof a}
function F(a,b,c){for(var d in b)if(b.hasOwnProperty(d)&&(c||!a.hasOwnProperty(d))){var e=va(b[d]);if("object"===e||"array"===e){var f=va(a[d]);"object"!==f&&"array"!==f&&(a[d]="object"===e?{}:[]);F(a[d],b[d],c)}else a[d]=b[d]}}var G={},wa={};function H(a,b){xa();var c=setTimeout(a,b);G[c]=!0;return c}function ya(a){a&&(delete G[a],clearTimeout(a))}var za=!1;
function xa(){za||(I(function(){for(var a in G)G.hasOwnProperty(a)&&ya(parseInt(a,10));for(a in wa)if(wa.hasOwnProperty(a)){var b=parseInt(a,10);b&&(delete wa[b],clearInterval(b))}}),za=!0)}function I(a){var b=qa("bds.comm.registerUnloadHandler");"function"===typeof b?b(a):sa(function(){I(a)})};function Aa(a){this.p=a||document;Ba(this)}p=Aa.prototype;p.g=function(a){return"[object String]"===Object.prototype.toString.call(a)?this.p.getElementById(a):a&&a.nodeName&&(1===a.nodeType||9===a.nodeType)?a:null};p.J=null;p.N=null;function Ca(a){var b=A;b.J=a;var c=b.p.head||b.p.getElementsByTagName("head")[0]||b.p.body;c.insertBefore(a,c.firstChild);b.J=null}
function Da(){var a=A;if(a.J)return a.J;if(a.N&&"interactive"===a.N.readyState)return a.N;for(var b=a.p.getElementsByTagName("script"),c=b.length;c--;){var d=b[c];if("interactive"===d.readyState)return a.N=d}return null}p.remove=function(a){(a=this.g(a))&&a.parentNode&&a.parentNode.removeChild(a)};
p.getPosition=function(a){a=this.g(a);var b=a.ownerDocument||a.document,c={left:0,top:0},d=t&&!fa;if(a===(d?b.body:b.documentElement))return c;if(a.getBoundingClientRect)a=a.getBoundingClientRect(),c.left=Math.floor(a.left)+Math.max(b.documentElement.scrollLeft,b.body.scrollLeft),c.top=Math.floor(a.top)+Math.max(b.documentElement.scrollTop,b.body.scrollTop),c.left-=b.documentElement.clientLeft,c.top-=b.documentElement.clientTop,a=b.body,b=parseInt(this.getStyle(a,"borderLeftWidth"),10),a=parseInt(this.getStyle(a,
"borderTopWidth"),10),d&&(c.left-=isNaN(b)?2:b,c.top-=isNaN(a)?2:a);else{d=a;do{c.left+=d.offsetLeft;c.top+=d.offsetTop;if(0<ga&&"fixed"===this.getStyle(d,"position")){c.left+=b.body.scrollLeft;c.top+=b.body.scrollTop;break}d=d.offsetParent}while(d&&d!==a);if(0<ca||0<ga&&"absolute"===this.getStyle(a,"position"))c.top-=b.body.offsetTop;for(d=a.offsetParent;d&&d!==b.body;)c.left-=d.scrollLeft,ca&&"TR"===d.tagName||(c.top-=d.scrollTop),d=d.offsetParent}return c};
function K(a){var b=A;a=b.g(a);b=b.getPosition(a);b.width=a.offsetWidth;b.height=a.offsetHeight;return b}p.opacity=function(a,b){a=this.g(a);var c=t&&9>t;return null!=b||0===b?(c?(c=a.style,c.filter=""+(c.filter||"").replace(/alpha\([^\)]*\)/gi,"")+(1===b?"":"alpha(opacity="+100*b+")"),c.zoom=1):a.style.opacity=b,""):c?(c=a.style.filter)&&0<=c.indexOf("opacity=")?parseFloat(c.match(/opacity=([^)]*)/)[1])/100+"":"1":this.getStyle(a,"opacity")};
p.contains=function(a,b){a=this.g(a);b=this.g(b);return a.contains?a!==b&&a.contains(b):!!(a.compareDocumentPosition(b)&16)};p.getComputedStyle=function(a,b){a=this.g(a);var c=a.ownerDocument;return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b):""};
p.getStyle=function(a,b){a=this.g(a);b=la(b);var c=(a.currentStyle?a.currentStyle[b]:"")||this.getComputedStyle(a,b);if(!c||"auto"===c){var d=L[b];d&&(c=d.get?d.get(a,b,c):this.getStyle(a,d))}if(M)for(var d=b,e=0,f;f=M[e];e++)(f=f.get)&&(c=f(d,c));return c};var L=L||{};L.display=t&&8>t?{set:function(a,b){var c=a.style;"inline-block"===b?(c.display="inline",c.zoom=1):c.display=b}}:ba&&3>ba?{set:function(a,b){a.style.display="inline-block"===b?"-moz-inline-box":b}}:null;L["float"]=t?"styleFloat":"cssFloat";
L.opacity=t&&9>t?{get:function(a){return(a=a.style.filter)&&0<=a.indexOf("opacity=")?parseFloat(a.match(/opacity=([^)]*)/)[1])/100+"":"1"},set:function(a,b){var c=a.style;c.filter=(c.filter||"").replace(/alpha\([^\)]*\)/gi,"")+(1==b?"":"alpha(opacity="+100*b+")");c.zoom=1}}:null;var M=M||[];M[M.length]={get:function(a,b){if(/color/i.test(a)&&-1!==b.indexOf("rgb(")){var c=b.split(",");b="#";for(var d=0,e;e=c[d];d++)e=parseInt(e.replace(/[^\d]/gi,""),10).toString(16),b+=1===e.length?"0"+e:e;b=b.toUpperCase()}return b}};
M[M.length]={set:function(a,b){b.constructor!==Number||/zIndex|fontWeight|opacity|zoom|lineHeight/i.test(a)||(b+="px");return b}};function Ea(a,b,c,d){b=a.g(b);for(a=b[d];a;a=a[c])if(1===a.nodeType)return a;return null}p=Aa.prototype;p.first=function(a){return Ea(this,a,"nextSibling","firstChild")};p.next=function(a){return Ea(this,a,"nextSibling","nextSibling")};p.prev=function(a){return Ea(this,a,"previousSibling","previousSibling")};
p.getAncestorBy=function(a,b){for(a=this.g(a);(a=a.parentNode)&&1===a.nodeType;)if(b(a))return a;return null};p.insertBefore=function(a,b){var c;a=this.g(a);b=this.g(b);(c=b.parentNode)&&c.insertBefore(a,b);return a};
p.q=function(a,b,c){var d=[],e,f,h;if(!(a=C(a)))return d;if("undefined"===typeof b)b=this.p;else if(b=this.g(b),!b)return d;c&&(c=C(c).toUpperCase());if(b.getElementsByClassName)for(f=b.getElementsByClassName(a),b=f.length,e=0;e<b;e++)h=f[e],c&&h.tagName!==c||(d[d.length]=h);else for(a=RegExp("(^|\\s)"+String(a).replace(RegExp("([.*+?^=!:${}()|[\\]/\\\\-])","g"),"\\$1")+"(\\s|$)"),f=c?b.getElementsByTagName(c):b.all||b.getElementsByTagName("*"),b=f.length,e=0;e<b;e++)h=f[e],a.test(h.className)&&(d[d.length]=
h);return d};
function Ba(a){a.Ha||(a.Ha=function(){function b(){if(!b.isReady){b.isReady=!0;for(var a=0,c=d.length;a<c;a++)d[a]()}}var c=!1,d=[];(function(){if(!c){c=!0;var d=a.p,f=window;if(t&&f===top)(function(){if(!b.isReady){try{d.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}b()}})();else if(d.addEventListener){var h=ca?function(){if(!b.isReady){for(var a=0;a<d.styleSheets.length;a++)if(d.styleSheets[a].disabled){setTimeout(arguments.callee,0);return}b()}}:b;d.addEventListener("DOMContentLoaded",
h,!1);I(function(){d.removeEventListener("DOMContentLoaded",h,!1)})}else if(aa){var k;(function(){if(!b.isReady)if("loaded"!==d.readyState&&"complete"!==d.readyState)setTimeout(arguments.callee,0);else{if(void 0===k){k=0;var a=d.getElementsByTagName("style"),c=d.getElementsByTagName("link");a&&(k+=a.length);if(c)for(var a=0,f=c.length;a<f;a++)"stylesheet"===c[a].getAttribute("rel")&&k++}d.styleSheets.length!==k?setTimeout(arguments.callee,0):b()}})()}f.attachEvent?(f.attachEvent("onload",b),I(function(){f.detachEvent("onload",
b)})):f.addEventListener&&(f.addEventListener("load",b,!1),I(function(){f.removeEventListener("load",b,!1)}))}})();return function(a){b.isReady?a():d[d.length]=a}}())}var A=new Aa;var N={},Fa=[];function Ga(a,b){function c(){d++;d>=e&&b.apply(null,Ha(a))}"string"===typeof a&&(a=[a]);for(var d=0,e=a.length,f=0;f<e;f++)Ia(a[f],c)}function Ha(a){for(var b=[],c=0;c<a.length;c++)b.push(N[a[c]]||null);return b}
function Ia(a,b){function c(){var a=d.readyState;if("undefined"===typeof a||/^(?:loaded|complete)$/.test(a))if(a=d.src,d=d.onload=d.onreadystatechange=null,N[a])b(N[a]);else{var c=Fa.pop();c&&(N[a]=c,b(c))}}if(N[a])b(N[a]);else{var d=Ka();d.src=a;document.addEventListener?d.onload=c:d.readyState&&(d.onreadystatechange=c);Ca(d)}}function Ka(){var a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.async=!0;return a}
window.ECMA_define=window.ECMA_define||function(a){var b=Da();b?(a=a(),(b=b.src)?N[b]=a:Fa.push(a)):(b=a(),Fa.push(b))};window.ECMA_require=window.ECMA_require||function(a,b){Ga(a,b)};function La(a){this.K=u({closeBoardRenderUrl:"http://ecma.bdimg.com/public03/imageplus/v2/dailog/close_board.app.js"},this.K||{});this.A=u(this.K,a)}La.prototype.get=function(a,b){return a in this.A?this.A[a]:b};function Ma(a,b,c){this.u="f21ac82b21eeb7322631b6aa94e17f45"+E();this.O=c;this.Aa=this.render();a.insertBefore(this.Aa,a.firstChild);Na(this,b)}function Na(a,b){var c=A.g(a.u+"-icon");x(c,"mouseover",function(a){ja(a);if(a=c.nextSibling)a.style.display="block";b("tipmouseover")});x(c,"mouseout",function(a){ja(a);if(a=c.nextSibling)a.style.display="none";b("tipmouseout")});x(c,"click",function(a){ja(a);b("tipclick")})}
Ma.prototype.render=function(){var a="#${domId} {position:absolute;top:0;left:0;right:auto;bottom:auto;margin:0;padding:0;border:0;width:200px;background:transparent;-webkit-box-sizing:content-box;box-sizing:content-box;}#${domId} div{float:left;width:144px;height:17px;line-height:17px;margin:3px 0 0 -2px;background:url(${TIP_BACK_URL}) 0 0 no-repeat;_background:0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',sizingMethod='corp',src='${TIP_BACK_URL}');font-family:sans-serif;text-align:center;font-size:12px;color:#666;padding:8px 10px;display:none;-webkit-box-sizing:content-box;box-sizing:content-box;}#${domId}-icon {float:left;height:38px;width:38px;cursor:default;background:url(${ICON_URL}) 0 0 no-repeat;_background:0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',sizingMethod='corp',src='${ICON_URL}');-webkit-box-sizing:content-box;box-sizing:content-box;}#${domId}-icon:hover {float:left;height:38px;width:38px;}#${domId} #${domId}-icon:hover {background:url(${ICON_HOVER_URL}) 0 0 no-repeat;_background:0;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',sizingMethod='corp',src='${ICON_HOVER_URL}');}";this.O&&
(a+="#${domId}-icon {width:34px;height:34px;margin:2px 0 0 2px;cursor:pointer;}#${domId}-icon:hover {width:34px;height:34px;}");var b=document.createElement("div");b.id=this.u;b.innerHTML='<a href="javascript:void(0);" id="'+this.u+'-icon"></a>'+(this.O?"":'<div id="'+this.u+'-msg">\u67e5\u770b\u6807\u8bc6\u83b7\u53d6\u66f4\u591a\u4fe1\u606f</div>');var c=b.childNodes[0],a=ka(a,{domId:this.u,TIP_BACK_URL:"http://ecma.bdimg.com/public03/imageplus/tip-back.png",ICON_URL:this.O?"http://ecma.bdimg.com/public03/imageplus/i_2.png":
"http://ecma.bdimg.com/public03/imageplus/tip.png",ICON_HOVER_URL:this.O?"http://ecma.bdimg.com/public03/imageplus/i_2.png":"http://ecma.bdimg.com/public03/imageplus/tip-hover.png"}),d=A.p,e=c.parentNode;if(e){var f=d.createElement("style");f.type="text/css";f.media="screen";e.insertBefore(f,c);f.styleSheet?f.styleSheet.cssText=a:f.appendChild(d.createTextNode(a))}return b};function O(a){this.d=this.m=0;this.a=[];this.L=[];this.config=a;this.ya=Math.ceil(new Date/36E5);this.U={};this.r=null;this.$=!1}O.prototype.ca=function(){};O.prototype.pa=function(){};O.prototype.qa=function(){};
function Oa(a,b){var c=a.getImgIndex(b);if(!c){var c=++a.d,d=a.pa(b),e=function(b){R(a,b.relatedTarget||b.fromElement,c)||a.b(c,"mouseover")},f=function(b){R(a,b.relatedTarget||b.toElement,c)||a.b(c,"mouseout")},h=function(){a.b(c,"mousemove")};x(d,"mouseover",e);x(d,"mouseout",f);x(d,"mousemove",h);x(b,"mouseover",e);x(b,"mouseout",f);x(b,"mousemove",h);x(b,"click",function(){a.b(c,"clickimg")});a.a[c]={f:b,h:d,s:{},oa:{},t:{},o:{},aa:0,F:{},T:"",Ja:null,Ia:!1};a.m++}return c}
function R(a,b,c){a=a.a[c];if(!a||null==b)return!1;if(a.f===b||A.contains(a.h,b))return!0;var d=!1;a.links&&B(a.links,function(a){if(a===b||A.contains(a,b))return d=!0,!1});return d}
function Pa(a,b,c,d){var e="string"===typeof c?c:c.url,f="string"===typeof c?"":c.id,h=new S(a,b),k=h.getImgWrapper();k&&(c=e,c=-1!==c.indexOf("?")?c+"&":c+"?",c+="cacheTime="+a.ya,ECMA_require(c,function(c){var n=a.a[b];if(null!=n&&A.contains(document.documentElement,k)){a.U[e]||(a.U[e]=c.get("AD_CONFIG"));var g={};F(g,a.U[e]);var m=d.id||g.id||"f21ac82b21eeb7322631b6aa94e17f45"+b+E();d.id=m;a.b(b,"renderloaded",e,m);var l=a.config.get("adConfig");l&&F(g,l,!0);F(g,d,!0);g.api=h;c.set("AD_CONFIG",
g);g=document.createElement("div");g.id=m;g.style.margin="0px";g.style.padding="0px";g.style.border="none";g.style.overflow="visible";g.style.textAlign="left";k.appendChild(g);n.s[m]=g;n.t[m]="canvasopen";n.o[m]={id:f,url:e};n.aa++;h.l=m;c=c.start(!0,!0);n.oa[m]=c}}))}O.prototype.ba=function(a){var b=this,c=b.a[a];if(c&&!c.T){var d=new Ma(c.h,function(){var c=[].slice.call(arguments,0);c.unshift(a);b.b.apply(b,c)},b.$);c.T=d.u;c.Ja=d}};
function Qa(a,b,c){function d(a){var b={},c;for(c in a)if(a.hasOwnProperty(c)){var e=va(a[c]);if("object"===e||"array"===e){if("object"!==e||a[c].constructor===Object)b[c]=d(a[c])}else b[c]=a[c]}return b}var e=a.a[b];a=e.oa;var e=e.o,f=c||"ALL";c=[];if("[object Array]"===Object.prototype.toString.call(f))c=f;else if("ALL"===f)for(var h in a)a.hasOwnProperty(h)&&c.push(h);else c=[f];f=[];b="f21ac82b21eeb7322631b6aa94e17f45closeBoardCavnasId"+b;for(var k=0;k<c.length;k++)if(h=c[k],h!==b){var q=e[h];
f.push({renderId:q.id,renderUrl:q.url,data:d(a[h].adConfig)})}return f}O.prototype.closeAd=function(a,b,c){var d=this.a[a],e=d.s,d=d.t;if("ALL"===b){for(var f in e)e.hasOwnProperty(f)&&(e[f].style.display="none",d[f]="canvasclose");this.b(a,"hide");this.b(a,"onclose",c)}else e[b].style.display="none",d[b]="canvasclose",this.fire(a,b,"hide"),this.fire(a,b,"onclose",c)};
O.prototype.b=function(a,b,c){if(3<arguments.length){var d=Array.prototype.slice.call(arguments);d.shift();d.unshift("ALL");d.unshift(a);this.fire.apply(this,d)}else this.fire(a,"ALL",b,c)};
O.prototype.fire=function(a,b,c,d){var e=this.L[a];if(e){var f;"string"!==typeof c&&(f=c,c=c.type);if((e=e[c])&&0!==e.length){var h=Array.prototype.slice.call(arguments,3);f?f.imgIndex=a:f={imgIndex:a,id:E(),type:c};h.unshift(f);for(var k="ALL"===b,q,n=0,g=e.length;n<g;n++)f=e[n],q=f.canvas,(k||"ALL"===q||q===b)&&f.func.apply(null,h)}}};O.prototype.getImgIndex=function(a){if("number"===typeof a)return a;for(var b=this.a,c=1,d=b.length;c<d;c++)if(b[c]&&b[c].f===a)return c;return 0};
O.prototype.j=function(a){for(var b=this.a,c=1,d=b.length;c<d;c++)if(b[c]&&b[c].f===a)return b[c];return null};function U(a,b){for(var c=a.a,d=1,e=c.length;d<e;d++)c[d]&&b(c[d],d)}O.prototype.recordKey=function(a,b,c,d){if(a=this.a[a])a.F[b]=a.F[b]||[],a.F[b].push("string"===typeof c?{type:c,time:d}:c)};O.prototype.addListener=function(a,b,c,d){var e=this.L[a];e||(e=this.L[a]={});e[c]||(e[c]=[]);e[c].push({canvas:b,func:d})};function S(a,b){this.c=a;this.d=b;this.l="";this.version="1.0.6"}
S.prototype.j=function(){return this.c.a[this.d]};S.prototype.rendDone=function(a){var b=this.c,c;"object"===typeof a?(c=a.showTip,this.c.$=null!=a.useV2Tip?a.useV2Tip:this.c.$):c=a;c&&b.ba(this.d);b.a[this.d].Ia=!0};S.prototype.addListener=function(a,b){this.c.addListener(this.d,this.l,a,b)};S.prototype.getImg=function(){var a=this.j();return a?a.f:null};S.prototype.getImgWrapper=function(){var a=this.j();return a?a.h:null};
S.prototype.getCanvas=function(){var a=this.j();return a&&a.s?a.s[this.l]:null};S.prototype.getImgIndex=function(){return this.d};S.prototype.getImgRect=S.prototype.getAdRect=function(){var a=this.j();return a.rect||K(a.f)};S.prototype.setShareData=function(a,b,c){var d=this.c;if(c)d.r=d.r||{},d.r[a]=b;else if(c=d.a[this.d])c.S=c.S||{},c.S[a]=b};S.prototype.getShareData=function(a,b){if(b){var c=this.c.r;return c?c[a]||null:null}return(c=this.j())&&c.S?c.S[a]:null};
S.prototype.recordKey=function(a,b){this.c.recordKey(this.d,this.l,a,b)};S.prototype.recordTime=S.prototype.recordKey;S.prototype.getRecordedKey=function(){var a=this.j();return a&&a.F?a.F[this.l]:null};S.prototype.getRecordedTime=S.prototype.getRecordedKey;S.prototype.getRenderUrl=function(){var a=this.j();return a&&a.o?a.o[this.l].url||"":""};S.prototype.getRenderId=function(){var a=this.j();return a&&a.o?a.o[this.l].id||"":""};
S.prototype.getLoaderConfig=function(a,b){var c=this.c.config;return c.get.apply(c,arguments)};
S.prototype.closeAd=function(a){var b={usePrompt:!0,reasons:"",availableReasons:null,canvas:"ALL",closeBy:"AD"};F(b,a||{},!0);a=b.canvas;if("string"===typeof a)"ME"===a.toUpperCase()&&(a=this.l,b.canvas=this.l);else for(var c=0;c<a.length;c++)"ME"===a[c].toUpperCase()&&(a[c]=this.l);if(b.usePrompt){b.materials=Qa(this.c,this.d,b.canvas);a=this.c;var c=this.d,d=a.a[c],e="f21ac82b21eeb7322631b6aa94e17f45closeBoardCavnasId"+c,f=d.t[e];if("canvasloading"!==f&&"canvasopen"!==f)if("canvasclose"===f)if(d=
a.a[c],b=d.s,d=d.t,"ALL"===e){for(var h in b)b.hasOwnProperty(h)&&(b[h].style.display="block",d[h]="canvasopen");a.b(c,"show");a.b(c,"reopen")}else b[e].style.display="block",d[e]="canvasopen",a.fire(c,e,"show"),a.fire(c,e,"reopen");else if(h=a.config.get("closeBoardRenderUrl"))d.t[e]="canvasloading",b=b||{},b.id=e,Pa(a,c,{url:h,id:"closeBoardRenderId"},b)}else for(h=[],h="string"===typeof a?[a]:a,c=0;c<h.length;c++)this.c.closeAd(this.d,h[c],b.reasons)};
S.prototype.triggerAll=function(a,b){if(2<arguments.length){var c=Array.prototype.slice.call(arguments);c.unshift(this.d);this.c.b.apply(this.c,c)}else this.c.b(this.d,a,b)};S.prototype.getRenderInfos=function(){var a=this.j(),b=[];if(!a||!a.o)return b;var a=a.o,c={},d,e;for(e in a)a.hasOwnProperty(e)&&(d=a[e],c[d.id]||(c[d.id]=!0,b.push({id:d.id,url:d.url})));return b};S.prototype.getEnv=function(){return{from:"desktop"}};S.prototype.inView=function(){var a=this.j();return a?a.inView:!0};function V(a){var b={top:0,left:0,width:0,height:0};if(Ra(a))return b;var c=a.baiduImageplusOverflowParent;if(c&&Sa(c))return Ta(a,c);if((c=a.baiduImageplusHiddenParent)&&Ra(c))return b;var d=!1,e=!1,f=null,c=baidu.dom.getAncestorBy(a,function(b){var c=A.getStyle(b,"position");if("absolute"===c||"fixed"===c)e=!0;if(Ra(b))return d=!0;if(e&&"static"===c||!Sa(b))return!1;f=Ta(a,b);return f.clipped});if(!c)return K(a);if(d)return a.baiduImageplusHiddenParent=c,b;a.baiduImageplusOverflowParent=c;return f}
function Ra(a){return"none"===A.getStyle(a,"display")||"0"===A.getStyle(a,"opacity")||"hidden"===A.getStyle(a,"visibility")}function Sa(a){if("HTML"===a.nodeName||"BODY"===a.nodeName)return!1;var b=A.getStyle(a,"display"),c=A.getStyle(a,"float");return"inline"!==b||"none"!==c&&""!==c?"visible"!==A.getStyle(a,"overflow")?!0:!1:!1}
function Ta(a,b){var c=K(a),d=K(b),e=c.top,f=c.left,h=c.width,k=c.height,q=d.top,n=d.left,g=d.width,d=d.height;if(e>=q&&f>=n&&f+h<=n+g&&e+k<=q+d)return c.clipped=!1,c;c={clipped:!0};f>n?(c.left=f,c.width=g-(f-n)):(c.left=n,c.width=h-(n-f));c.width=Math.min(c.width,h,g);e>q?(c.top=e,c.height=d-(e-q)):(c.top=q,c.height=k-(q-e));c.height=Math.min(c.height,k,d);return c};function W(a){this.M=a.get("imgRectKey","baiduImageplusRect");O.call(this,a);(a=baidu.cookie.get("baiduImageplusQid"))&&baidu.cookie.remove("baiduImageplusQid",{path:"/"});a=this.na=a||E()+(new Date).getTime();this.r=this.r||{};this.r.qid=a;this.la=this.config.get("maxAdCount");this.ja=this.config.get("maxMiniAdCount");this.D=this.la+this.ja;this.H=this.I=0;this.n={};this.ua={};this.ta=document.getElementsByTagName("img").length;this.va=!1;this.xa=[];this.za=this.Z=0;this.V=null;this.ma=this.Y=0;
this.wa=this.config.get("noLogo");this.ka=this.config.get("maxMultiFormImgCount");this.B=(this.W=this.config.get("formList"))?this.W.length:0}baidu.inherits(W,O);function Ua(a){a=(a=a.config.get("imgContainerId"))?A.g(a):document;return baidu.lang.toArray("img"===a.nodeName.toLowerCase()?[a]:a.getElementsByTagName("img"))}p=W.prototype;
p.ca=function(){function a(){Va(b);b.fa();b.va=!0;B(b.xa,function(a){a()})}var b=this;b.config.get("autoStart")&&("complete"===document.readyState?a():x(window,"load",a))};function Va(a){var b=a.m;0<b&&U(a,function(b,c){Wa(a,c)});if(b<a.D){var c=Ua(a),d=function(){if(c.length&&!(a.m>=a.D)){var b=c.shift();Xa(a.config,b)?a.da(b,function(c){c?(Ya(a,b),H(d,500)):d()}):d()}};d()}}function Za(a){var b;try{b=decodeURIComponent(a.src)}catch(c){b=ma(a.src)}return b}
function $a(a,b){if(!b)return!1;switch(b){case 1:return a.ma<a.ja;case 2:return a.Y<a.la;default:return!1}}
p.da=function(a,b){var c=this,d=c.getImgIndex(a);if(d)Wa(c,d),b&&b(d);else if(c.m>=c.D)b&&b(0);else if(ab(c,a))b&&b(0);else{var e=(new Date).getTime();bb(a,function(d){if(!d||c.m>=c.D)b&&b(0);else{d=a[c.M]=V(a);var h=X(c.config,d);if($a(c,h)){var k=(new Date).getTime();c.getData(a,function(d){if(d&&$a(c,h)){var f=(new Date).getTime(),g;try{g=decodeURIComponent(a.src)}catch(m){g=a.src}for(var l,v,D,z,J=!1,P=!1,pb=function(a,b,d){if(a.imgIndex===l){for(var g in c.n)c.n.hasOwnProperty(g)&&c.recordKey(l,
d,g,c.n[g]);c.recordKey(l,d,"found",e);c.recordKey(l,d,"loading",k);c.recordKey(l,d,"loaded",f);c.recordKey(l,d,"render_loaded",(new Date).getTime());c.recordKey(l,d,"ad_count",c.Z);c.recordKey(l,d,"pg_rect",cb());a=Q.rect;c.recordKey(l,d,"img_rect",[a.top,a.left,a.width,a.height].join("_"))}},na=0,qb=d.length;na<qb;na++)if(v=d[na],D=v.ads,D.length){for(var oa=0,rb=D.length;oa<rb;oa++)if(z=D[oa],g===z.image){var Ja=db(c,v.render);if(Ja){z.position_type=v.position_type;z.exp_list=v.exp_list;v.box&&
(z.box=z.box||{},F(z.box,v.box,!0));if(!P){J=a[c.M];l=Oa(c,a);c.Z++;1===h?c.ma++:c.Y++;var Q=c.a[l],P=V(a);Q.rect=J||P;X(c.config,P)?Q.inView=eb(c,a):(Q.inView=!1,Q.h.style.display="none");P=!0;c.addListener(l,"ALL","renderloaded",pb)}Pa(c,l,{url:Ja,id:v.render_id},z);J=!0}}J&&fb(c,l)}b&&b(l||0)}else b&&b(0)},{imgType:h})}else b&&b(0)}})}};
function db(a,b){var c=a.config.get("renderReplaceRules");if(!c)return b;for(var d in c)if(c.hasOwnProperty(d)){var e=RegExp(d);if(b.match(e))return(c=c[d])?b.replace(e,c):""}return b}
p.R=function(a){if(a=this.getImgIndex(a)){this.ra(a);var b=this.a[a];if(b){var c=b.s,d=b.t,e=b.o;this.b(a,"release");for(var f in c)c.hasOwnProperty(f)&&(A.remove(f),c[f]=null,d[f]=null,e.ALL=null,b.aa--);0<b.aa||(b.T&&A.remove(b.T),f=b.f,y(f,"mouseover"),y(f,"mousemove"),y(f,"mouseout"),y(f,"click"),b=b.h,y(b,"mouseover"),y(b,"mousemove"),y(b,"mouseout"),this.qa(a),this.a[a]=null,this.L[a]=null,this.m--)}this.Z--}};
p.pa=function(a){var b=document.createElement("div");b.style.cssText="position:absolute;border:0;margin:0;padding:0;height:0;overflow:visible;text-align:left;";gb(b,a);document.body.appendChild(b);var c=a[this.M];a[this.M]=null;hb(this,c,b);return b};
function hb(a,b,c){b=b.nodeName?V(b):b;var d=a.V;d||("static"===A.getStyle(document.body,"position")?a.V=d={top:0,left:0}:a.V=d=baidu.dom.getPosition(document.body));c.style.top=b.top-d.top+"px";c.style.left=b.left-d.left+"px";c.style.width=b.width+"px"}p.qa=function(a){(a=this.a[a])&&A.remove(a.h)};
p.getData=function(a,b,c){if(location.href.match(/(\?|&)baiduImageplus=/))b(window.baiduImagePlusFakeData);else{c=1===(c||{}).imgType;var d=this,e,f,h;if(a.nodeName&&"img"===a.nodeName.toLowerCase()){e=Za(a);if(f=d.ua[e]){b(f);return}f=d.config.get("apiWd");"function"===typeof f&&(f=f(a));f=encodeURIComponent(f);h=a.offsetWidth;a=a.offsetHeight}else e=a.image,f=a.wd||"",h=a.width,a=a.height;var k=d.config.get("api"),q=d.config.get("unionId"),n={src:d.config.get("apiSrc"),k:f,"iurl[]":e,qid:d.na,tu:q,
width:h,height:a,opt:d.n.opt||"",v:d.n.v||"",cached:0,pic:d.ta},k=k+(-1===k.indexOf("?")?"?":"&"),g=0;e=function(a,b){var c={dri:++d.za};b&&d.B&&(F(c,d.W[g%d.B]),g++);F(c,n);baidu.sio.callByServer(k+pa(c),a,{charset:"gbk",timeOut:1E4,onfailure:a})};if(c||1>=d.B)e(b,!c);else if(0<=d.ka&&d.Y>=d.ka)e(b,!0);else{var m=[],l=0;c=function(a){a&&m.push(a);l++;l>=d.B&&b(Array.prototype.concat.apply([],m))};for(a=0;a<d.B;a++)e(c,!0)}}};
function bb(a,b){if(a.complete)b(!0);else{var c=function(){b(!0);y(a,"load",c)};x(a,"load",c);var d=function(){b(!1);y(a,"abort",d);y(a,"error",d)};x(a,"abort",d);x(a,"error",d)}}function ib(a,b,c){var d=[];c?(d[0]=c,d[1]=b):(d[0]=a.getImgIndex(b),d[1]=a.a[d[0]]);return d[0]&&d[1]?d:null}
p.ea=function(a,b){var c=ib(this,a,b);if(c){var d=c[0],c=c[1];if(A.contains(document.documentElement,c.f)){var e=V(c.f),f=c.rect;if(e.top!==f.top||e.left!==f.left||e.width!==f.width||e.height!==f.height)if(c.rect=e,X(this.config,e))hb(this,e,c.h),Wa(this,d),gb(c.h,c.f),this.b(d,"resize",e);else if(d=this.getImgIndex(d))c=this.a[d],c.inView=!1,c.h.style.display="none",this.b(d,"hide")}else this.R(d)}};function Wa(a,b){var c=a.a[b];c.h.style.display="block";c.inView=eb(a,c.f);a.b(b,"show")}
p.sa=function(){var a=this;U(a,function(b,c){a.ea(b,c)})};p.fa=function(){var a=this;jb(function(){a.m&&(kb(a),U(a,function(b,c){a.ea(b,c);lb(a,b,c)}))});mb(function(){a.m&&U(a,function(b,c){lb(a,b,c)})})};function jb(a){var b;x(window,"resize",function(){b&&ya(b);var c=arguments,d=this;b=H(function(){a.apply(d,c);b=null},500)})}
function mb(a){function b(){d=h;c=null;a.apply(e,f);e=f=null}var c,d,e,f,h;x(window,"scroll",function(){e=this;f=arguments;h=(new Date).getTime();d=d||h;var a=1E3-(h-d);0>=a?(ya(c),b()):c||(c=H(b,a))})}function lb(a,b,c){var d=eb(a,b.f);b.inView!==d&&(b.inView=d,a.b(c,d?"intoview":"outview"));d&&a.b(c,"inview")}function eb(a,b){a.I=a.I||baidu.page.getViewWidth();a.H=a.H||baidu.page.getViewHeight();var c=b.getBoundingClientRect();return 0<c.bottom&&c.top<a.H&&0<c.right&&c.left<a.I}
function kb(a){a.I=baidu.page.getViewWidth();a.H=baidu.page.getViewHeight()}function Ya(a,b){function c(a){(a="."===a.charAt(0)?baidu.q(a.replace(/^\./,"")):A.g(a.replace(/^#/,"")))&&(baidu.lang.isArray(a)?a.length&&B(a,function(a){d.P(a,f,e)}):d.P(a,f,e))}var d=a,e=b?d.getImgIndex(b):1,f=d.a[e];if(f){var h=d.config.get("imgCoverId");h&&c(h);(h=d.config.get("imgCovers"))&&B(h.split(","),c)}}
p.P=function(a,b,c){var d=this;if(b=ib(d,b,c)){var e=b[0];b=b[1];b.links=b.links||[];b.w=b.w||[];c=function(a){R(d,a.relatedTarget||a.fromElement,e)||d.b(e,"mouseover")};var f=function(a){R(d,a.relatedTarget||a.toElement,e)||d.b(e,"mouseout")},h=function(){d.b(e,"mousemove")},k=function(){d.b(e,"clickimg")};b.links.push(a);b.w.push({mouseover:c,mouseout:f,mousemove:h,click:k});x(a,"mouseover",c);x(a,"mouseout",f);x(a,"mousemove",h);x(a,"click",k);gb(b.h,a)}};
function gb(a,b){var c;var d=b,e=d;for(c=[d];(e=e.offsetParent)&&"body"!==e.nodeName.toLowerCase();)"static"!==A.getStyle(e,"position")&&(d=e,c.push(d));if(6===t)c=parseInt(A.getStyle(d,"z-index"),10)||0;else{for(e=0;c.length;)d=c.pop(),d=parseInt(A.getStyle(d,"z-index"),10),isNaN(d)||(e=Math.max(d,e));c=e}d=parseInt(A.getStyle(a,"z-index"),10)||0;c>d&&(a.style.zIndex=c+10)}
p.Ka=function(a,b){var c=this.getImgIndex(b);if(c&&(c=this.a[c],c.links)){var d=baidu.array.indexOf(c.links,a);if(-1!==d){var e=c.w[d],f;for(f in e)e.hasOwnProperty(f)&&y(a,f,e[f]);baidu.array.removeAt(c.links,d);baidu.array.removeAt(c.w,d)}}};p.ra=function(a){if(a=this.getImgIndex(a)){var b=this.a[a];b.links&&(B(b.links,function(a,d){var e=b.w[d],f;for(f in e)e.hasOwnProperty(f)&&y(a,f,e[f])}),b.links.length=0,b.w.length=0)}};
function fb(a,b){if(a.config.get("autoDetectCover")){var c=a.config.get("findCoverLevel");if(!(0>=c)){var d=a.a[b];if(d){var e=d.f,f=-1,h={BODY:!0,HEAD:!0,SCRIPT:!0,STYLE:!0,META:!0,HTML:!0},k=function(q,n){if(!(f>=c||h[q.nodeName])){f++;var g;if(g=0!==n)if("a"===q.nodeName.toLowerCase()?g=!0:(g=A.getStyle(q,"cursor"),g="pointer"===g||0===g.indexOf("url(")),g&&(g=!A.contains(q,e))){g=K(q);var m=d.rect,l=g.top,v=g.left,D=m.top,z=m.left,v=Math.abs(v-z)<(v>z?m.width:g.width);g=Math.abs(l-D)<(l>D?m.height:
g.height)&&v}g&&a.P(q,d,b);4!==n&&(g=baidu.dom.first(q))&&k(g,1);3!==n&&(g=baidu.dom.next(q))&&k(g,2);2!==n&&(g=baidu.dom.prev(q))&&k(g,3);(0===n||4===n)&&(g=q.parentNode)&&k(g,4);f--}};k(e,0)}}}}function ab(a,b){var c=!1;U(a,function(a){c||a.h&&(c=A.contains(a.h,b))});return c}function cb(){var a=baidu.page.getViewHeight(),b=baidu.page.getViewWidth(),c=baidu.page.getScrollTop(),d=baidu.page.getScrollLeft();return[c,d,b,a].join("_")}p.ba=function(){this.wa||W.superClass.ba.apply(this,arguments)};function Y(a){this.ia=a.get("imgStatusKey","baiduImageplusStatus");this.ha=a.get("imgSnapshotKey","baiduImageplusSnapshot");this.X=!1;W.call(this,a)}baidu.inherits(Y,W);
Y.prototype.ca=function(){var a=this;if(a.config.get("autoStart")){a.n.opt=1;a.n.v=8;var b=a.config.get("startOnLoad"),c,d=function(){function d(){a.m<a.D&&nb(a);a.sa();H(d,a.config.get("tickInterval"))}b&&(a.n.onload=(new Date).getTime());c&&clearTimeout(c);d();a.fa()};b&&"complete"!==document.readyState?(x(window,"load",d),c=setTimeout(d,a.config.get("onloadTimeout"))):d()}};
function nb(a){var b=Ua(a),c=a.ia;B(b,function(b){if(b&&Xa(a.config,b))switch(b[c]||0){case 0:ob(a,b);break;case 1:var e=sb(b),f=b[a.ha],h=!1,k;for(k in e)if(e.hasOwnProperty(k)&&e[k]!==f[k]){h=!0;break}h&&(b[c]=1,ob(a,b))}})}function ob(a,b){var c={};if(c.immediate||!a.X)a.X=!0,a.da(b,function(d){a.X=!1;var e=a.ia;d?(b[e]=2,Ya(a,b)):(b[e]=1,b[a.ha]=sb(b));c.callback&&c.callback(d)})}
function sb(a){return{src:a.src,opacity:A.getStyle(a,"opacity"),visibility:A.getStyle(a,"visibility"),width:a.offsetWidth,height:a.offsetHeight}}Y.prototype.R=function(a){var b=a;if("number"===typeof b)if(b=this.a[b])b=b.f;else return;b.baiduImageplusStatus=0;Y.superClass.R.call(this,a)};function tb(a){this.K=u({autoStart:!0,imgContainerId:"",ignoredContainers:"",imgCoverId:"",imgCovers:"",apiSrc:1E3,apiWd:function(a){return a.alt||document.title},api:"http://imageplus.baidu.com/ui",minImgWidth:300,minImgHeight:200,maxAdCount:4,minMiniImgWidth:200,minMiniImgHeight:180,maxMiniAdCount:2,autoDetectCover:!0,findCoverLevel:4,supportGIF:!1,noLogo:!1,maxMultiFormImgCount:1},this.K||{});La.call(this,a);this.Ba=this.get("supportGIF")?/.(?:html|htm)(?:$|#|\?)/:/.(?:gif|html|htm)(?:$|#|\?)/;
this.minWidth=parseInt(this.get("minImgWidth"),10);this.minHeight=parseInt(this.get("minImgHeight"),10);this.Ga=parseInt(this.get("minMiniImgWidth"),10);this.Fa=parseInt(this.get("minMiniImgHeight"),10);(a=C(this.get("unionId")))&&0===a.indexOf("u")&&(a=a.slice(1));this.A.unionId=a;this.C=null}baidu.inherits(tb,La);
function ub(a,b){var c=a.get("ignoredContainers");if(!c)return!1;a.C||(a.C=[],B(c.split(","),function(b){b="."===b.charAt(0)?baidu.q(b.slice(1)):[A.g(b.slice(1))];a.C=a.C.concat(b)}));var d=!1;B(a.C,function(a){if(a&&A.contains(a,b))return d=!0,!1});return d}function Xa(a,b){var c=b.getAttributeNode("data-baiduimageplus-ignore");return c&&c.specified||a.Ba.test(b.src)||ub(a,b)?!1:!!X(a,{width:b.offsetWidth,height:b.offsetHeight})}
function X(a,b){var c=b.width,d=b.height;return d>=a.minHeight&&c>=a.minWidth?2:d>=a.Fa&&c>=a.Ga?1:0};function vb(a){tb.call(this,a);this.A=u({tickInterval:1E3,onloadTimeout:5E3,startOnLoad:!1},this.A)}baidu.inherits(vb,tb);var wb=window.cpro_id||"",Z=window.baiduImagePlus||{},xb={};wb&&(window.cpro_id=null);!Z.unionId&&wb&&(Z.unionId=wb);
function yb(a){var b=new Y(new vb(a||Z));b.n=xb;b.ca();window.baiduImagePlus={_status:"loaded",_loader:b,showAd:function(){return b.da.apply(b,arguments)},removeAd:function(){return b.R.apply(b,arguments)},updateAd:function(){return b.ea.apply(b,arguments)},updateAds:function(){return b.sa.apply(b,arguments)},watchAds:function(){return b.fa.apply(b,arguments)},linkAd:function(){return b.P.apply(b,arguments)},unlinkAd:function(){return b.Ka.apply(b,arguments)},unlinkAds:function(){return b.ra.apply(b,
arguments)}}}if("loading"!==Z._status&&"loaded"!==Z._status){Z._status="loading";window.baiduImagePlus=Z;xb.start=(new Date).getTime();var $=Z.api||"http://imageplus.baidu.com/ui",$=$+(-1===$.indexOf("?")?"?":"&")+"api=config&tu="+C(Z.unionId||"").replace(/^u/,"")+"&pic="+document.getElementsByTagName("img").length;baidu.sio.callByServer($,function(a){xb.site_api_loaded=(new Date).getTime();a=a||{};yb(u(a,Z))},{charset:"gbk",timeOut:1E4,onfailure:yb})};

})(/** AD_CONFIG */{}, /** LINKS */[], /** RT_CONFIG */{});
//Thu Apr 09 2015 18:23:07 GMT+0800 (CST)